name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'  # Only trigger on changes to backend directory

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./backend  # Change to backend directory
        run: |
          npm install

      - name: Build
        working-directory: ./backend
        run: |
          npm run build --if-present  # Run build if it exists

      # Zip the backend directory for deployment
      - name: Zip Backend Directory
        run: |
          cd backend
          zip -r ../backend-deploy.zip ./*

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'goscroll-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './backend-deploy.zip'  # Deploy the zipped package

      - name: Log Deploy Status
        run: |
          echo "Deployment completed"